import Head from 'next/head'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Login from '../components/Login';
import { getProviders, getSession, useSession } from "next-auth/react";
import { useRecoilValue } from "recoil";
import { modalState } from "../atoms/modalAtom";
import Modal from '../components/Modal';

export default function Home({ providers }) {
  const { data: session } = useSession();
  const isOpen = useRecoilValue(modalState);

  if (!session) {
    return <Login providers={providers} />
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen flex max-w-[1500px] mx-auto'>
        <Sidebar />
        <Feed />

        {isOpen && <Modal />}
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session
    }
  }
}